apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  selector:
    matchLabels:
      app: p-ser-zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: p-ser-zookeeper
    spec:
      containers:
        - name: zookeeper-container
          image: bitnami/zookeeper:3.9
          ports:
            - containerPort: 2181
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  selector:
    matchLabels:
      app: p-ser-kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: p-ser-kafka
    spec:
      containers:
        - name: kafka-container
          image: bitnami/kafka:3.4
          ports:
            - containerPort: 9092
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper-service.message-ns.svc.cluster.local:2181
            - name: KAFKA_CFG_BROKER_ID
              value: "0"
            - name: KAFKA_ZOOKEEPER_PROTOCOL
              value: PLAINTEXT
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:29092,EXTERNAL://:9092
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-service.message-ns.svc.cluster.local:29092,EXTERNAL://kafka-service.message-ns.svc.cluster.local:9092
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: p-ser-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: p-ser-redis
    spec:
      containers:
        - name: redis-container
          image: bitnami/redis:7.0.15-debian-12-r17
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              value: "1234"