apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  selector:
    matchLabels:
      app: p-ser-zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: p-ser-zookeeper
    spec:
      containers:
        - name: zookeeper-container
          image: confluentinc/cp-zookeeper:7.0.1
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: 2181
            - name: ZOOKEEPER_TICK_TIME
              value: 2000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  selector:
    matchLabels:
      app: p-ser-kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: p-ser-kafka
    spec:
      containers:
        - name: kafka-container
          image: confluentinc/cp-kafka:7.0.1
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service.kafka-ns.svc.cluster.local:2181
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INTERNAL
            - name: KAFKA_LISTENERS
              value: INTERNAL://:29092,PLAINTEXT://:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INTERNAL://kafka-service.kafka-ns.svc.cluster.local:29092,EXTERNAL://kafka-service.kafka-ns.svc.cluster.local:9092

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: p-ser-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: p-ser-redis
    spec:
      containers:
        - name: redis-container
          image: redis
          ports:
            - containerPort: 6379