apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
  selector:
    app: p-ser-zookeeper

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
    - name: kafka-port
      port: 9092
    - name: kafka-port-internal
      port: 29092
  type: ClusterIP
  clusterIP: None
  selector:
    app: p-ser-kafka

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  ports:
    - name: redis-port
      port: 6397
  type: ClusterIP
  clusterIP: None
  selector:
    app: p-ser-redis